export samples in CI. call yarn project compilation synchronously in more locations

diff --git a/.github/workflows/continuous_build_check.yaml b/.github/workflows/continuous_build_check.yaml
--- a/.github/workflows/continuous_build_check.yaml
+++ b/.github/workflows/continuous_build_check.yaml
@@ -9,7 +9,9 @@ on:
       - '**/*.md'
       - 'docs/**'
 env:
-  GODOT_CLI: ./godot/godot.x86_64
+  DOTNET_CLI_TELEMETRY_OPTOUT: true
+  DOTNET_NOLOGO: true
+  
 defaults:
   run:
     shell: bash
@@ -20,7 +22,7 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        godotDownload: ["https://downloads.tuxfamily.org/godotengine/4.1.3/mono/Godot_v4.1.3-stable_mono_linux_x86_64.zip", "https://downloads.tuxfamily.org/godotengine/4.2/mono/Godot_v4.2-stable_mono_linux_x86_64.zip"]
+        godotVersion: ["4.1.3", "4.2.0"]
         targetFramework: ["net6.0", "net7.0"]
     name: Build
     runs-on: ubuntu-latest
@@ -36,20 +38,42 @@ jobs:
       - name: Set Target Framework ${{ matrix.targetFramework }}
         run: |
           sed -i 's|<TargetFramework>.*<|<TargetFramework>'${{ matrix.targetFramework }}'<|g' YarnSpinner-Godot.csproj
-      
-      - name: Download Godot
-        id: downloadGodot
+
+      - uses: chickensoft-games/setup-godot@v1
+        name: 🤖 Setup Godot
+        with:
+          version: ${{ matrix.godotVersion}}
+          # Use .NET-enabled version of Godot (the default is also true).
+          use-dotnet: true
+
+      - name: 🔬 Verify Setup
         run: |
-          wget -O godot.zip ${{ matrix.godotDownload }}
-          unzip godot.zip
-          mv ./Godot_v4* ./godot
-          touch ./godot/.gdignore
-          mv ./godot/*.x86_64 $GODOT_CLI
+          dotnet --version
+          godot --version
           
       - name: Build solution
         id: buildSolution
         run: |
-          $GODOT_CLI --headless --path . --verbose -q -e --build-solutions --quit 
-          # sometimes --build-solutions still exits with code 0, so double check
+          godot --headless --path . --verbose -e --build-solutions --quit 
           dotnet build
         timeout-minutes: 2
+        
+      - name: Export samples
+        id: exportSamples
+        run: |
+
+          exportPath=./build/linux64_debug/YarnSpinner-GodotSamples.x86_64
+          mkdir -p "$(dirname $exportPath)"
+          godot --headless --path . --verbose --export-debug linux_x86_64 "$exportPath" --quit 
+          if ! test -f "$exportPath"; then
+            echo "::error::Failed to export the debug samples to $exportPath"
+            exit 1
+          fi
+          exportPath=./build/linux64/YarnSpinner-GodotSamples.x86_64
+          mkdir -p "$(dirname $exportPath)"
+          godot  --headless --path . --verbose --export-release linux_x86_64 "$exportPath" --quit 
+          if ! test -f "$exportPath"; then
+            echo "::error::Failed to export the release samples to $exportPath"
+            exit 1
+          fi
+        timeout-minutes: 6
